### ISSUE TITLE
icon in Actions menu does not play nice in dark theme

### ISSUE THREAD

**Issue by bwana147** [nextcloud/files_zip#110]
This is really just a nice-to-have: using a dark theme, the icon that appears in the Actions menu, once you have selected files, is hard to see, as it is black on a dark gray background. I suppose that there must be a way of providing two sets of icons, one for light themes and one for dark ones.

**Comment by meichthys** [comment]
This still seems to be an issue in v1.1.2 and NC v25.0.3RC3
![image](https://user-images.githubusercontent.com/10717998/219042643-74071a18-ccba-4a39-a791-e528c7788cbf.png)
