### ISSUE TITLE
Whats this?

### ISSUE THREAD

**Issue by twerpyfie** [nextcloud/files_zip#123]
Hello,

i found this in the code:

```
                    Ht = "\t\n\v\f\r Â áš€â€€â€â€‚â€ƒâ€„â€…â€†â€‡â€ˆâ€‰â€Šâ€¯âŸã€€\u2028\u2029\ufeff",
                    Jt = "[" + Ht + "]",
                    Xt = RegExp("^" + Jt + Jt + "*"),
                    Kt = RegExp(Jt + Jt + "*$"),
                    Yt = function(t) {
                        return function(e) {
                            var n = String(b(e));
                            return 1 & t && (n = n.replace(Xt, "")), 2 & t && (n = n.replace(Kt, "")), n
                        }
                    },
```

What does it do? 
It looks like its some sort of Obfuscation

**Comment by juliushaertl** [comment]
Can you provide some more details where you have found this? We don't obfuscate code. The javascript bundles in the release assets may contain minified code but the map files are included so you should be able to unwrangle them with standard browser tools.

**Comment by twerpyfie** [comment]
Hello, somehow I forgot to specify that, sorry. I do not know what is wrong with me. xD

I can't find this exact code anymore, but there are other parts that look like this in the file /js/files_zip-main.js. You just have to search for regex. Thanks for the quick reply and have a nice day.

**Comment by joshtrichards** [comment]
Pretty certain the file you actually want to look at is https://github.com/nextcloud/files_zip/blob/main/src/main.js

You're looking at the compiled asset. You can see how it's built here:

https://github.com/nextcloud/webpack-vue-config/blob/master/webpack.config.js

https://webpack.js.org/guides/getting-started/#basic-setup

And some of the "why":

https://webpack.js.org/concepts/why-webpack/

If you're used to just browsing the PHP assets on a NC installation, the front end assets being pseudo-compiled may come as a surprise.

**Comment by juliushaertl** [comment]
Thanks @joshtrichards for jumping in and adding more context. Let me close this then.
