### ISSUE TITLE
Installing when running PHP7.4 breaks Nextcloud

### ISSUE THREAD

**Issue by chriscroome** [nextcloud/files_zip#136]
On a Nextcloud server running on Debian Bullseye with PHP7.4 installing `files_zip` results in a requirement for PHP8.0 which causes Nextcloud to only serve HTTP 500 errors, when using `occ` there is this message:

```
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.33.
```

**Comment by juliushaertl** [comment]
How do you install the app? There is no composer involved in the final release package.

**Comment by chriscroome** [comment]
I didn't install it, but as far as I'm aware it was done using the Nextcloud web based admin interface.

I've added PHP 8.0 to the server now -- there didn't seem to be any way to get it working again other than rolling back the server or installing a newer PHP.

**Comment by mbh-dev** [comment]
The app was installed from the nextcloud app store by simply clicking on download and install.

This then broke the server by changing some config file somewhere by requiring PHP 8.0 but couldn't find the JSON file that forced this change, therefore requiring that the server be upgraded to PHP 8.0 even after disabling and removing the file_zip app

**Comment by juliushaertl** [comment]
Was there any log trace that pointed to files_zip as there is no composer usage in the release tarball as far as I'm aware and can see from the latest release.

**Comment by chriscroome** [comment]
Sorry I couldn't find anything of interest in the logs,myself and @mbh-dev were physically sat next to each other at the time this happened and we were not aware of any other changes that were made to the server, all we could put the sudden requirement for `a PHP version ">= 8.0.2"` down to was installing `files_zip`.

**Comment by joshtrichards** [comment]
The only reference I see to this output is here: https://github.com/nextcloud/3rdparty/blob/master/composer/platform_check.php

And the reference to 8.0.2 was added in nextcloud/3rdparty#1311 and would have started appearing first in NC27 (which already required PHP 8.0). Oh, and this related one nextcloud/server#36617. The weird thing is none of this code was even merged into master until mid-April.

So this couldn't (shouldn't) haven't even been in-service for you unless you were running off master (`server`) or something. 

Was this on a production server? Are you guys using any sort of CI?

**Comment by chriscroome** [comment]
It was on a production server, @mbh-dev caused it when using the Nextcloud web UI as an admin.

The server was configured using Ansible but the issues wasn't caused by this.

The server has been since upgraded to run PHP 8.2 and the latest Nextcloud.

Sorry I don't know how exactly it happened, there is probably nothing else that can be done apart from closing this issue...
