### ISSUE TITLE
[F2V] Migrate to new file actions API

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/files_zip#165]
https://github.com/nextcloud/files_zip/blob/main/src/main.js should be migrated to the new file actions API.

https://nextcloud.github.io/nextcloud-files/functions/registerFileAction.html
https://nextcloud.github.io/nextcloud-files/classes/FileAction.html

@skjnldsv Can you share some light on the plans for backward compatibility of the file action APIs? Are there any compatibility layers planned or in place to put the old actions in the new action menu or the other way round? Anything else to be aware of apart from the api docs?

**Comment by skjnldsv** [comment]
> @skjnldsv Can you share some light on the plans for backward compatibility of the file action APIs? Are there any compatibility layers planned or in place to put the old actions in the new action menu or the other way round? Anything else to be aware of apart from the api docs?

None. New actions are replacing the old one.
Nonetheless we're not too far off the previous API in terms of method trigger, so the migration is quite straightforward

Ref: https://github.com/nextcloud/server/issues/37947
