### ISSUE TITLE
Which dependency do you use to zip ?

### ISSUE THREAD

**Issue by zak39** [nextcloud/files_zip#232]
Hi everyone :)

I would like to know which dependency do you use to zip in this project?

I see you use [ZipStreamer](https://github.com/nextcloud/files_zip/blob/bfac72a8b18c3a929e13cc2ce65b0a322f4a9611/lib/Service/ZipService.php#L125), but I don't see it in this composer.json.

You mention this github repository about ZipStreamer : https://github.com/DeepDiver1975/PHPZipStreamer/

Is the repository your dependency?

**Comment by juliushaertl** [comment]
zipstreamer is part of the 3rdparty dependencies that the server provides https://github.com/nextcloud/3rdparty/tree/master/deepdiver/zipstreamer, therefore we rely on the bundled version instead having it in our own composer dependencies.

**Comment by juliushaertl** [comment]
We use what is in 3rdparty, we added a fork of it to nextcloud-deps but meanwhile the library is still maintained upstream. Consider the deps repo as just a mirror (even though slightly outdated)

**Comment by zak39** [comment]
Thanks for your answer :)
