### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by rullzer** [nextcloud/files_zip#4]
@tobiasKaminsky maybe once done adding support for this to the mobile clients would be a nice idea?

**Comment by tobiasKaminsky** [comment]
If it is officially supported by us, sure.
We can then already brainstorm the api.

- add to capability -> files -> zip: true|false
- endpoint accepts 
  - list of file ids (which can also be folders)
  - target folder
  - name (?)
  --> then creates in background zip file and adds notification
