### ISSUE TITLE
Translations Issue

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/files_zip#60]
Hello,
I don't understand when I go to my files on my instance and I click to create a ZIP, the text is in English while the translations of the application are good.

**Comment by juliushaertl** [comment]
Can you tell which text you are referring to exactly and on which language?

**Comment by JordanDIG** [comment]
> Can you tell which text you are referring to exactly and on which language?

French

**Comment by JordanDIG** [comment]
@juliushaertl

**Comment by juliushaertl** [comment]
And which text is it exactly that is showing in english?

**Comment by JordanDIG** [comment]
> And which text is it exactly that is showing in english?

Yes :/

**Comment by JordanDIG** [comment]
The Extract button

**Comment by juliushaertl** [comment]
Could you check again on the latest release? The translation should have been shipped with https://github.com/nextcloud/files_zip/releases/tag/v1.1.0 now
