### ISSUE TITLE
Zip single file action

### ISSUE THREAD

**Issue by Pablo1732** [nextcloud/files_zip#71]
I don't have a "Zip" button in the right-click menu in the Files app

**Comment by marcosvfc** [comment]
Clean installation of NC24 on Ubuntu 22.04 (also fresh install), no button "Zip"

**Comment by juliushaertl** [comment]
So currently only multi select is supported, but lets keep this as an enhancement request to add a file action for single files.

**Comment by StarSmasher44** [comment]
Here's a tip, if you were planning to download the zip file any way....

Put all your files into a folder, then right click... Download folder. It makes a .zip that is identical to this one instantly, no waiting around required in this case :)
