### ISSUE TITLE
Unable to zip files

### ISSUE THREAD

**Issue by Giusemx** [nextcloud/files_zip#84]
Hi, 
i have a self hosted nextcloud. I installed zipper, but i am not able to zip files. I become the notification, that the zip file will be created, but the zip file never appear or will be finished.
I tried the same on a nextcloud from hetzner, and that works fine. So i think, it's a configuration issue of nextcloud or i need an extension or similar?
I didn't find a log with the information too.
I hope you can help me.

Best regards

**Comment by Giusemx** [comment]
update: So i see, the zip file is now created. It taked very long time.. 2 days.. So, what is the problem?
I think resources, but wich one can be the cause?

Thanks a lot in advance.

**Comment by StarSmasher44** [comment]
What was the size of the folder you tried to zip? As this zipping utility only stores it in .zip format and applies no compression at all it shouldn't take too long.

Either that, or perhaps the cron job (or however it is triggered every X amt of time) took a while to trigger. I've had it take a few minutes before, potentially even an hour but not more than that.

I find it a bit of an awful system as you get 0 indication of when it is done, or when it starts, or if it has started or anything like that.. 

If you want a faster way to zip files, use the built-in system. Slap everything into a single folder, select folder and hit 'Download'. It gets zipped up instantly, all you have to do is whatever you wanted to with the zip.

**Comment by Giusemx** [comment]
A tried a simple jpeg file and 2 pdf files. I become the message, that it beginn to zip, and i got the message, that the zipping is finish. But after 1-2 days. So it's somewhere an option or whatever, where i can set it?

**Comment by juliushaertl** [comment]
The Zip file is generated in a background job, so please check if you have properly setup that one using cron as the recommended way: https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/background_jobs_configuration.html
